"""Add popularity_score to events again

Revision ID: 53e59bb60130
Revises: 103fae6ca79c
Create Date: 2026-02-08 16:03:59.865203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53e59bb60130'
down_revision = '103fae6ca79c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('popularity_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'popularity_score')
    # ### end Alembic commands ###
